[package]
name = "confine-macro"
version = "0.1.4"
edition = "2024"
authors = ["Fabian Diez <contact@fdiez.tech>"]
homepage = "https://github.com/fabiandiez/confine-rs"
repository = "https://github.com/fabiandiez/confine-rs"
license = "MIT OR Apache-2.0"
description = "Macro implementation for the confine crate"
categories = ["config"]
keywords = ["config", "configuration", "macro", "config-rs"]

[lib]
proc-macro = true

[dependencies]
darling = "0.23"
quote = "1.0"
syn = { version = "2.0", features = ["full"] }
thiserror = "2.0"

confine-builder = { path = "../confine-builder", version = "0.1.4" }